# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

    commit-message:
      prefix: ci
    labels: ["skip changelog"]

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.spigotmc:spigot-api"  # We want to stay on 1.18 for the base version
        versions: ["< 1.19"]
      - dependency-name: "com.sk89q.worldguard:worldguard-bukkit"  # v7.0.10+ is compiled with a newer Java version.
        versions: ["< 7.0.10"]
      - dependency-name: "com.sk89q.worldedit:worldedit-bukkit"  # v7.3.4+ is compiled with a newer Java version.
