name: ${project.name}
description: ${project.description}
version: ${project.version}
main: com.rngservers.graves.Main
api-version: 1.13
author: RandomUnknown

commands:
  graves:
    description: Graves info
    default: true
    usage: /graves
    aliases: [graves, grave, deathchests, deathchest, dc, death]

permissions:
  graves.place:
    default: true
    description: Can place a graves
  graves.open:
    default: true
    description: Can open a grave
  graves.autoloot:
    default: true
    description: Can Autoloot a grave
  graves.break:
    default: true
    description: Can break a grave
  graves.gui:
    default: true
    description: Can view graves
  graves.gui.other:
    default: op
    description: Can view other peoples graves
  graves.teleport:
    default: true
    description: Can teleport to grave
  graves.bypass:
    default: op
    description: Bypass grave protection
  graves.reload:
    default: op
    description: Reload Graves
  graves.cleanup:
    default: op
    description: Cleanup holograms