name: ${project.name}
description: ${project.description}
version: ${project.version}
main: com.ranull.graves.Graves
api-version: 1.13
author: Ranull
load: POSTWORLD
loadbefore:
  - GriefPrevention
  - XItemsRemover
softdepend:
  - Vault
  - WorldEdit
  - WorldGuard
  - GriefDefender
  - PlaceholderAPI
  - FurnitureLib
  - FurnitureEngine
  - ProtectionLib
  - ChestSort
  - ItemsAdder
  - Oraxen
  - ItemBridge
  - ProtocolLib
  - SkullTextureAPI
  - Skript

commands:
  graves:
    description: Graves info
    default: true
    usage: /graves
    aliases:
      - grave
      - deathchests
      - deathchest
      - dc
      - death

permissions:
  graves.place:
    default: true
    description: Can place a graves
  graves.open:
    default: true
    description: Can open a grave
  graves.autoloot:
    default: true
    description: Can Autoloot a grave
  graves.break:
    default: true
    description: Can break a grave
  graves.gui:
    default: true
    description: Can view graves
  graves.gui.other:
    default: op
    description: Can view other peoples graves
  graves.experience:
    default: true
    description: Can store experience in graves
  graves.protection:
    default: true
    description: Can have protection on graves
  graves.teleport:
    default: true
    description: Can teleport to grave
  graves.bypass:
    default: op
    description: Bypass grave protection
  graves.dump:
    default: op
    description: Dump server information
  graves.debug:
    default: op
    description: Change debug level
  graves.givetoken:
    default: op
    description: Give a grave token
  graves.reload:
    default: op
    description: Reload Graves
