name: ${project.name}
description: ${project.description}
version: ${project.version}
main: org.avarion.graves.Graves
api-version: 1.18
author: Ranull, svaningelgem
load: POSTWORLD

loadbefore:
  - Towny

softdepend:
  - Vault
  - ProtocolLib
  - WorldEdit
  - WorldGuard
  - PlaceholderAPI
  - FurnitureLib
  - FurnitureEngine
  - ProtectionLib
  - MineDownPlugin
  - ChestSort
  - ItemsAdder
  - Oraxen
  - ProtocolLib
  - SkullTextureAPI
  - ItemBridge
  - PlayerNPC
  - Skript
  - CoreProtect

commands:
  graves:
    description: Graves command
    usage: /graves
    aliases:
      - grave
      - tombstones
      - tombstone
      - deathchests
      - deathchest
      - deaths
      - death
      - tombs
      - tomb
      - dc

  graveyards:
    description: Graveyards command
    usage: /graveyards
    aliases:
      - graveyard
      - cemeteries
      - cemetery
      - burialgrounds
      - burialground
      - churchyards
      - churchyard
      - necropolises
      - necropolis
      - gy

permissions:
  graves.place:
    default: true
    description: Can place a graves

  graves.open:
    default: true
    description: Can open a grave

  graves.autoloot:
    default: true
    description: Can Autoloot a grave

  graves.break:
    default: true
    description: Can break a grave

  graves.gui:
    default: true
    description: Can view graves

  graves.gui.other:
    default: op
    description: Can view other peoples graves

  graves.experience:
    default: true
    description: Can store experience in graves

  graves.protection:
    default: true
    description: Can have protection on graves

  graves.teleport:
    default: true
    description: Can teleport to grave

  graves.bypass:
    default: op
    description: Bypass grave protection

  graves.dump:
    default: op
    description: Dump server information

  graves.purge:
    default: op
    description: Purge graves

  graves.cleanup:
    default: op
    description: Cleanup graves

  graves.debug:
    default: op
    description: Change debug level

  graves.update.notify:
    default: op
    description: Notify player about plugin update

  graves.import:
    default: op
    description: Import graves from another plugin

  graves.givetoken:
    default: op
    description: Give a grave token

  graves.graveyard:
    default: true
    description: Graveyard menu

  graves.reload:
    default: op
    description: Reload Graves
